# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
      
    - name: Install Allure CLI
      run: | 
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        allure --version

    - name: Build with Maven
      run: mvn clean test -fae || true

    - name: Run post-test commands and generate Allure report
      run: |
        cd core_product_tests
        allure generate src/test/resources/reports/allure-results --clean -o allure-report_cp
        cd ..
        cd derived_product_1_tests
        allure generate src/test/resources/reports/allure-results --clean -o allure-report_dp1
        cd ..
        cd derived_product_2_tests
        allure generate src/test/resources/reports/allure-results --clean -o allure-report_dp2
        cd ..

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    
    - name: Upload Allure HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report_cp
        path: core_product_tests/src/test/resources/reports/allure-report_cp
    - name: Upload Allure HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report_dp1
        path: derived_product_1_tests/src/test/resources/reports/allure-report_dp1
    - name: Upload Allure HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report_dp2
        path: derived_product_2_tests/src/test/resources/reports/allure-report_dp2
